### ISSUE TITLE
How is disqualification defined?

### ISSUE THREAD

**Issue by yannbouteiller** [microsoft/AirSim-NeurIPS2019-Drone-Racing#43]
Hello,

I am having a hard time understanding the new rule for disqualification. For what I understood so far, the leading drone (closest to the next gate center) would disqualify the other drone if he got within the collision radius, but this seems not to be the case in the released binary. I need this information for my reward function to work accordingly.

**Comment by yannbouteiller** [comment]
Disqualification doesn't work in according to the guidelines when one drone has crossed more gates than another either. I have just tested crashing a drone that had crossed 2 gates into a drone that had crossed 1 gate, and the drone that had crossed 2 gates got disqualified.

**Comment by ironclownfish** [comment]
Thanks, we are looking into your logs.
Regarding the logs, you can delete or rename the RaceLogs folder to prevent new logs from being created.

**Comment by madratman** [comment]
please try with new release. should be fixed

**Comment by yannbouteiller** [comment]
Hello, I don't think I can reopen this issue, but it is not fixed. I don't understand how the leading drone is really defined for disqualification but it is definitely not the closest to the next gate center nor the drone that crossed the highest number of gates right now.

I need this information because I don't use logs since it is too slow and not convenient for very long trainings so I compute this by hand.

Actually, I think the software lacks an API function that returns race information such as who is leading/disqualified and the last crossed gate for each drone. For now I computed all this by hand and it is a little bit cumbersome.
